/*
####### Generated by JavaToTypeScript Wed Dec 19 16:22:47 SAST 2018
####### rigged up by AM Esq.
*/

import { JsonObject, JsonProperty } from "json2typescript";

@JsonObject('AdminDTO')
export class AdminDTO {
	@JsonProperty('adminID', String)
	adminID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('phone', String)
	phone: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('password', String)
	password: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('gcmID', String)
	gcmID: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: AdminDTO

@JsonObject('AggregatesRatingsDTO')
export class AggregatesRatingsDTO {
	@JsonProperty()
	driverAggregate: DriverAggregateRatingDTO;
	// @JsonProperty()
	// experienceAggregate: ExperienceAggregateRatingDTO;
	@JsonProperty()
	rankAggregate: RankAggregateRatingDTO;
	@JsonProperty()
	safetyAggregate: SafetyAggregateRatingDTO;
	@JsonProperty()
	vehicleAggregate: VehicleAggregateRatingDTO;
}


// ------------------- end of: AggregatesRatingsDTO

@JsonObject('AnnouncementDTO')
export class AnnouncementDTO {
	static ASSOCIATION = 0;
	static ROUTE = 0;
	static LANDMARK = 0;
	static ADMINS = 0;
	static MARSHALS = 0;
	static OWNERS = 0;
	static DRIVERS = 0;
	static PATROLLERS = 0;
	static COMMUTERS = 0;
	static ROUTE_BUILDERS = 0;
	@JsonProperty('includesCommuters', Boolean)
	includesCommuters: boolean;
	@JsonProperty('announcementID', String)
	announcementID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('title', String)
	title: string;
	@JsonProperty('message', String)
	message: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('priority', Number)
	priority: number;
	@JsonProperty('announcementType', Number)
	announcementType: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('expiryDate', Number)
	expiryDate: number;


//**** Handle this list: photoList

}


// ------------------- end of: AnnouncementDTO

@JsonObject('ApologyDTO')
export class ApologyDTO {
	@JsonProperty('apologyID', String)
	apologyID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('uid', String)
	uid: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('stackTrace', String)
	stackTrace: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('userMessage', String)
	userMessage: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('problemResolvedSent', Boolean)
	problemResolvedSent: boolean;
	@JsonProperty('version', Number)
	version: number;
	@JsonProperty('versionCode', Number)
	versionCode: number;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: ApologyDTO

@JsonObject('AssociationDTO')
export class AssociationDTO {
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('phone', String)
	phone: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('countryName', String)
	countryName: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: AssociationDTO

@JsonObject('AttachmentDTO')
export class AttachmentDTO {
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('dateRegistered', Number)
	dateRegistered: number;
}


// ------------------- end of: AttachmentDTO

@JsonObject('AttachmentForVehicleDTO')
export class AttachmentForVehicleDTO {
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('make', String)
	make: string;
	@JsonProperty('model', String)
	model: string;
	@JsonProperty('capacity', Number)
	capacity: number;
}


// ------------------- end of: AttachmentForVehicleDTO

@JsonObject('BasicMessageDTO')
export class BasicMessageDTO {
	@JsonProperty('title', String)
	title: string;
	@JsonProperty('body', String)
	body: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('json', String)
	json: string;
	@JsonProperty('from', String)
	from: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: BasicMessageDTO

@JsonObject('BeaconLogDTO')
export class BeaconLogDTO {
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('updatedBy', String)
	updatedBy: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('removedFromVehicle', Boolean)
	removedFromVehicle: boolean;
	@JsonProperty('addedToVehicle', Boolean)
	addedToVehicle: boolean;
}


// ------------------- end of: BeaconLogDTO

@JsonObject('CityDTO')
export class CityDTO {
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('provinceID', String)
	provinceID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('provinceName', String)
	provinceName: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('countryName', String)
	countryName: string;
	@JsonProperty()
	builder: UserDTO;
	@JsonProperty('date', Number)
	date: number;


//**** Handle this list: routeList



//**** Handle this list: associationList

}


// ------------------- end of: CityDTO

@JsonObject('CommuterArrivalDTO')
export class CommuterArrivalDTO {
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('arrivalID', String)
	arrivalID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateArrived', Number)
	dateArrived: number;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	device: DeviceDTO;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('associationID', String)
	associationID: string;
}


// ------------------- end of: CommuterArrivalDTO

@JsonObject('CommuterDTO')
export class CommuterDTO {
	@JsonProperty('commuterID', Number)
	commuterID: number;
	@JsonProperty('gcmID', String)
	gcmID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('surname', String)
	surname: string;
	@JsonProperty('phone', String)
	phone: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('password', String)
	password: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('date', Number)
	date: number;


//**** Handle this list: photos

}


// ------------------- end of: CommuterDTO

@JsonObject('CommuterDepartureDTO')
export class CommuterDepartureDTO {
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('departureID', String)
	departureID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateDeparted', Number)
	dateDeparted: number;
	@JsonProperty()
	device: DeviceDTO;
	@JsonProperty()
	user: UserDTO;
}


// ------------------- end of: CommuterDepartureDTO

@JsonObject('CommuterFinishedDrivingDTO')
export class CommuterFinishedDrivingDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('make', String)
	make: string;
	@JsonProperty('model', String)
	model: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: CommuterFinishedDrivingDTO

@JsonObject('CommuterFinishedWalkingDTO')
export class CommuterFinishedWalkingDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('finishedWalkingID', String)
	finishedWalkingID: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: CommuterFinishedWalkingDTO

@JsonObject('CommuterLogDTO')
export class CommuterLogDTO {
	@JsonProperty('commuterLogID', String)
	commuterLogID: string;
	@JsonProperty('panicID', String)
	panicID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: CommuterLogDTO

@JsonObject('CommuterRequestDTO')
export class CommuterRequestDTO {
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('originLandmarkID', String)
	originLandmarkID: string;
	@JsonProperty('destinationLandmarkID', String)
	destinationLandmarkID: string;
	@JsonProperty('originLandmarkName', String)
	originLandmarkName: string;
	@JsonProperty('destinationLandmarkName', String)
	destinationLandmarkName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('freeRideVoucherID', String)
	freeRideVoucherID: string;
	@JsonProperty('commuterRequestID', String)
	commuterRequestID: string;
	@JsonProperty('stringDateUpdated', String)
	stringDateUpdated: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('pickUpID', String)
	pickUpID: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('expiryMinutes', Number)
	expiryMinutes: number;
	@JsonProperty('requestStartTime', Number)
	requestStartTime: number;
	@JsonProperty('requestEndTime', Number)
	requestEndTime: number;
	@JsonProperty('dateUpdated', Number)
	dateUpdated: number;
	@JsonProperty('tripDistance', Number)
	tripDistance: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('hour', Number)
	hour: number;
	@JsonProperty('minute', Number)
	minute: number;
	@JsonProperty('numberOfPassengers', Number)
	numberOfPassengers: number;
	@JsonProperty('cancelledByCommuter', Boolean)
	cancelledByCommuter: boolean;
	@JsonProperty('cancelledByAssociation', Boolean)
	cancelledByAssociation: boolean;
	@JsonProperty('expired', Boolean)
	expired: boolean;
	@JsonProperty('pickedUpNoScan', Boolean)
	pickedUpNoScan: boolean;
	@JsonProperty('requestStatus', String)
	requestStatus: string;
	@JsonProperty('stringDistance', String)
	stringDistance: string;
	@JsonProperty('stringTimeToDestination', String)
	stringTimeToDestination: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	pickUp: PickUpDTO;
}


// ------------------- end of: CommuterRequestDTO

@JsonObject('CommuterStartDrivingDTO')
export class CommuterStartDrivingDTO {
	@JsonProperty('commuterDrivingID', String)
	commuterDrivingID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('make', String)
	make: string;
	@JsonProperty('model', String)
	model: string;
	@JsonProperty('starting', Boolean)
	starting: boolean;
	@JsonProperty('stopping', Boolean)
	stopping: boolean;
	@JsonProperty('moving', Boolean)
	moving: boolean;
	@JsonProperty('beaconFound', Boolean)
	beaconFound: boolean;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('capacity', Number)
	capacity: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('bearing', Number)
	bearing: number;
	@JsonProperty('speed', Number)
	speed: number;
}


// ------------------- end of: CommuterStartDrivingDTO

@JsonObject('CommuterStartWalkingDTO')
export class CommuterStartWalkingDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('startWalkingID', String)
	startWalkingID: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: CommuterStartWalkingDTO

@JsonObject('CommuterTripLogDTO')
export class CommuterTripLogDTO {
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('commuterTripLogID', String)
	commuterTripLogID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	commuter: UserDTO;
}


// ------------------- end of: CommuterTripLogDTO

@JsonObject('CommuterVehicleDTO')
export class CommuterVehicleDTO {
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('commuterVehicleID', String)
	commuterVehicleID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('beaconID', String)
	beaconID: string;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('starting', Boolean)
	starting: boolean;
	@JsonProperty('stopping', Boolean)
	stopping: boolean;
}


// ------------------- end of: CommuterVehicleDTO

@JsonObject('ConfigDTO')
export class ConfigDTO {
	@JsonProperty('configID', String)
	configID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('driverLogStartHour', Number)
	driverLogStartHour: number;
	@JsonProperty('driverLogEndHour', Number)
	driverLogEndHour: number;
	@JsonProperty('driverLogFrequencyMinutes', Number)
	driverLogFrequencyMinutes: number;
	@JsonProperty('fenceDwellSeconds', Number)
	fenceDwellSeconds: number;
	@JsonProperty('pointsPerCommuterRequest', Number)
	pointsPerCommuterRequest: number;
	@JsonProperty('totalPointsForVoucher', Number)
	totalPointsForVoucher: number;
	@JsonProperty('numberOfDaysForValidVoucher', Number)
	numberOfDaysForValidVoucher: number;
	@JsonProperty('commuterRequestExpirationMinutes', Number)
	commuterRequestExpirationMinutes: number;
	@JsonProperty('safetyLogIntervalSeconds', Number)
	safetyLogIntervalSeconds: number;
	@JsonProperty('safetyLogPeriodHours', Number)
	safetyLogPeriodHours: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('adsOn', Boolean)
	adsOn: boolean;
	@JsonProperty('neuraOn', Boolean)
	neuraOn: boolean;
	@JsonProperty('hyperTrackOn', Boolean)
	hyperTrackOn: boolean;
	@JsonProperty('wifiTrackOnly', Boolean)
	wifiTrackOnly: boolean;
	@JsonProperty('region', String)
	region: string;
	@JsonProperty('language', String)
	language: string;
}


// ------------------- end of: ConfigDTO

@JsonObject('CountryDTO')
export class CountryDTO {
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;


//**** Handle this list: provinceList



//**** Handle this list: vehicleTypeList

}


// ------------------- end of: CountryDTO

@JsonObject('DeviceDTO')
export class DeviceDTO {
	@JsonProperty('model', String)
	model: string;
	@JsonProperty('manufacturer', String)
	manufacturer: string;
	@JsonProperty('androidVersion', String)
	androidVersion: string;
	@JsonProperty('serialNumber', String)
	serialNumber: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('userType', Number)
	userType: number;
	@JsonProperty('token', String)
	token: string;
}


// ------------------- end of: DeviceDTO

@JsonObject('DriverAggregateRatingDTO')
export class DriverAggregateRatingDTO {
}


// ------------------- end of: DriverAggregateRatingDTO

@JsonObject('DriverFinishedWalkingDTO')
export class DriverFinishedWalkingDTO {
	@JsonProperty('driverWalkingID', String)
	driverWalkingID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: DriverFinishedWalkingDTO

@JsonObject('DriverLogDTO')
export class DriverLogDTO {
	@JsonProperty('driverLogID', String)
	driverLogID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('nearestAddress', String)
	nearestAddress: string;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	landmark: LandmarkDTO;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('locationRequested', Boolean)
	locationRequested: boolean;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: DriverLogDTO

@JsonObject('DriverMarshalCampaignDTO')
export class DriverMarshalCampaignDTO {
	@JsonProperty('driverMarshalCampaignID', String)
	driverMarshalCampaignID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('startDate', Number)
	startDate: number;
	@JsonProperty('endDate', Number)
	endDate: number;
	@JsonProperty('dateRegistered', Number)
	dateRegistered: number;
	@JsonProperty('stringStartDate', String)
	stringStartDate: string;
	@JsonProperty('stringEndDate', String)
	stringEndDate: string;
	@JsonProperty('description', String)
	description: string;
	@JsonProperty('stringDateRegistered', String)
	stringDateRegistered: string;
	@JsonProperty('minimumTrips', Number)
	minimumTrips: number;
	@JsonProperty('minimumPickups', Number)
	minimumPickups: number;
	@JsonProperty('minimumCommuters', Number)
	minimumCommuters: number;
	@JsonProperty('pointValue', Number)
	pointValue: number;
	@JsonProperty('budget', Number)
	budget: number;
}


// ------------------- end of: DriverMarshalCampaignDTO

@JsonObject('DriverMarshalCampaignSummaryDTO')
export class DriverMarshalCampaignSummaryDTO {
	@JsonProperty('driverMarshalCampaignSummaryID', String)
	driverMarshalCampaignSummaryID: string;
	@JsonProperty('driverMarshalCampaignID', String)
	driverMarshalCampaignID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('dateOfCalculation', Number)
	dateOfCalculation: number;
	@JsonProperty('dateStart', Number)
	dateStart: number;
	@JsonProperty('dateEnd', Number)
	dateEnd: number;
	@JsonProperty('datePaid', Number)
	datePaid: number;
	@JsonProperty('stringDateOfCalculation', String)
	stringDateOfCalculation: string;
	@JsonProperty('stringDateStart', String)
	stringDateStart: string;
	@JsonProperty('stringDateEnd', String)
	stringDateEnd: string;
	@JsonProperty('stringDatePaid', String)
	stringDatePaid: string;
	@JsonProperty('description', String)
	description: string;
	@JsonProperty('totalTrips', Number)
	totalTrips: number;
	@JsonProperty('totalPickups', Number)
	totalPickups: number;
	@JsonProperty('totalCommuters', Number)
	totalCommuters: number;
	@JsonProperty('totalPoints', Number)
	totalPoints: number;
	@JsonProperty('userType', Number)
	userType: number;
	@JsonProperty('totalValue', Number)
	totalValue: number;
	@JsonProperty('percentageOfBudget', Number)
	percentageOfBudget: number;
	@JsonProperty('paid', Boolean)
	paid: boolean;
}


// ------------------- end of: DriverMarshalCampaignSummaryDTO

@JsonObject('ExpiredRequestDTO')
export class ExpiredRequestDTO {
	@JsonProperty('expiredRequestID', String)
	expiredRequestID: string;
	@JsonProperty('commuterRequestID', String)
	commuterRequestID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('expiredByMinutes', Number)
	expiredByMinutes: number;
}


// ------------------- end of: ExpiredRequestDTO

@JsonObject('FCMData')
export class FCMData {
	@JsonProperty('fromUser', String)
	fromUser: string;
	@JsonProperty('message', String)
	message: string;
	@JsonProperty('title', String)
	title: string;
	@JsonProperty('announcementID', String)
	announcementID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('json', String)
	json: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('expiryDate', Number)
	expiryDate: number;
	@JsonProperty('messageType', Number)
	messageType: number;
	static ANNOUNCEMENT = 0;
	static TRIP = 0;
	static INCIDENT = 0;
	static WELCOME = 0;
	static OTHER = 0;
	static COMMUTER_REQUEST = 0;
	static VEHICLE_LOCATION_REQUEST = 0;
	static VEHICLE_LOCATION_REQUEST_RESPONSE = 0;
	static RATING = 0;
	static ROUTE_UPDATE_TRIGGER = 0;
	static ROUTE_BUILDER_MESSAGE = 0;
	static ROUTE_ADDED = 0;
	static LANDMARK_ADDED = 0;
	static ROUTE_BUILDER_LOCATION_REQUEST = 0;
	static ROUTE_BUILDER_LOCATION_RESPONSE = 0;
	static USER_ADDED = 0;
	static ROUTE_DELETED = 0;
	static ROUTE_UPDATED = 0;
	static LANDMARK_DELETED = 0;
	static LANDMARK_UPDATED = 0;
	static FREE_RIDE_VOUCHER = 0;
	static FREE_RIDE_VOUCHER_REDEEMED = 0;
	static PICK_UP = 0;
	static PANIC = 0;
	static PANIC_OVER = 0;
	static MOVING_VEHICLE = 0;
	static MOVING_COMMUTER = 0;
	static HEART_BEAT = 0;
	static STOPPING_VEHICLE = 0;
	static TAXI_FEES = 0;
	static HYPERTRACK_TRIP_STARTED = 0;
	static HYPERTRACK_TRIP_ENDED = 0;
	static HYPERTRACK_STOP_STARTED = 0;
	static HYPERTRACK_STOP_ENDED = 0;
	static HYPERTRACK_USER_EVENT = 0;
	static PROBLEM_RESOLVED = 0;
}


// ------------------- end of: FCMData

@JsonObject('FavouriteDTO')
export class FavouriteDTO {
	@JsonProperty('favouriteID', Number)
	favouriteID: number;
	@JsonProperty('commuterID', Number)
	commuterID: number;
	@JsonProperty('cityID', Number)
	cityID: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('status', String)
	status: string;
}


// ------------------- end of: FavouriteDTO

@JsonObject('FreeRideCampaignDTO')
export class FreeRideCampaignDTO {
	@JsonProperty('freeRideCampaignID', String)
	freeRideCampaignID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('ownerName', String)
	ownerName: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('freeRideRandomizer', Number)
	freeRideRandomizer: number;
	@JsonProperty('startDate', Number)
	startDate: number;
	@JsonProperty('endDate', Number)
	endDate: number;
	@JsonProperty('freeRideMax', Number)
	freeRideMax: number;
	@JsonProperty('stringStartDate', String)
	stringStartDate: string;
	@JsonProperty('stringEndDate', String)
	stringEndDate: string;
	static ALL_FREE = 0;
	static NONE_FREE = 0;
}


// ------------------- end of: FreeRideCampaignDTO

@JsonObject('FreeRideVoucherDTO')
export class FreeRideVoucherDTO {
	@JsonProperty('freeRideVoucherID', String)
	freeRideVoucherID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringVoucherDate', String)
	stringVoucherDate: string;
	@JsonProperty('freeRideCampaignID', String)
	freeRideCampaignID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('userEmail', String)
	userEmail: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('marshalName', String)
	marshalName: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('stringDateRegistered', String)
	stringDateRegistered: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('stringDateRedeemed', String)
	stringDateRedeemed: string;
	@JsonProperty('userFCMtoken', String)
	userFCMtoken: string;
	@JsonProperty('driverFCMToken', String)
	driverFCMToken: string;
	@JsonProperty()
	userDTO: UserDTO;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('pickUpDate', Number)
	pickUpDate: number;
	@JsonProperty('voucherDate', Number)
	voucherDate: number;
	@JsonProperty('dateRegistered', Number)
	dateRegistered: number;
	@JsonProperty('dateRedeemed', Number)
	dateRedeemed: number;
	@JsonProperty('redeemed', Boolean)
	redeemed: boolean;
	@JsonProperty('numberOfRequests', Number)
	numberOfRequests: number;
	@JsonProperty('totalPassengers', Number)
	totalPassengers: number;
}


// ------------------- end of: FreeRideVoucherDTO

@JsonObject('FullTaxiDTO')
export class FullTaxiDTO {
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('ownerName', String)
	ownerName: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('marshalName', String)
	marshalName: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: FullTaxiDTO

@JsonObject('HeartbeatDTO')
export class HeartbeatDTO {
	@JsonProperty('heartbeatID', String)
	heartbeatID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: HeartbeatDTO

@JsonObject('IncidentDTO')
export class IncidentDTO {
	@JsonProperty('incidentID', String)
	incidentID: string;
	@JsonProperty('description', String)
	description: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('incidentType', String)
	incidentType: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('address', String)
	address: string;
	@JsonProperty()
	patroller: UserDTO;
	@JsonProperty()
	marshal: UserDTO;
	@JsonProperty()
	administrator: UserDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('dateReported', Number)
	dateReported: number;
}


// ------------------- end of: IncidentDTO

@JsonObject('LandmarkDTO')
export class LandmarkDTO {
	@JsonProperty('TAG', String)
	TAG: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('provinceID', String)
	provinceID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('rankSequenceNumber', Number)
	rankSequenceNumber: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('accuracy', Number)
	accuracy: number;
	@JsonProperty('cacheDate', Number)
	cacheDate: number;
	@JsonProperty()
	routeBuilder: UserDTO;
	@JsonProperty('gpsScanned', Boolean)
	gpsScanned: boolean;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('distanceFromMe', Number)
	distanceFromMe: number;
	@JsonProperty()
	mainRank: MainRankDTO;
	@JsonProperty('thisIsMainRank', Boolean)
	thisIsMainRank: boolean;
	@JsonProperty('virtualLandmark', Boolean)
	virtualLandmark: boolean;
	@JsonProperty('sortByRankSequence', Boolean)
	sortByRankSequence: boolean;
	@JsonProperty('sortByName', Boolean)
	sortByName: boolean;
	@JsonProperty('sortByDistance', Boolean)
	sortByDistance: boolean;
}


// ------------------- end of: LandmarkDTO

@JsonObject('MainRankDTO')
export class MainRankDTO {
	@JsonProperty('nickName', String)
	nickName: string;
}


// ------------------- end of: MainRankDTO

@JsonObject('MarshalArrivalDTO')
export class MarshalArrivalDTO {
	@JsonProperty('arrivalID', String)
	arrivalID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateArrived', Number)
	dateArrived: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: MarshalArrivalDTO

@JsonObject('MarshalDepartureDTO')
export class MarshalDepartureDTO {
	@JsonProperty('departureID', String)
	departureID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateDeparted', Number)
	dateDeparted: number;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: MarshalDepartureDTO

@JsonObject('MarshalLandmarkDTO')
export class MarshalLandmarkDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('marshalName', String)
	marshalName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: MarshalLandmarkDTO

@JsonObject('MarshalLogDTO')
export class MarshalLogDTO {
	@JsonProperty('marshalLogID', Number)
	marshalLogID: number;
	@JsonProperty('marshalID', Number)
	marshalID: number;
	@JsonProperty('landmarkID', Number)
	landmarkID: number;
	@JsonProperty('loginDate', Number)
	loginDate: number;
	@JsonProperty('logoutDate', Number)
	logoutDate: number;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: MarshalLogDTO

@JsonObject('MarshalRouteDTO')
export class MarshalRouteDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('marshalRouteID', String)
	marshalRouteID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('marshalName', String)
	marshalName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;


//**** Handle this list: landmarkIDs

}


// ------------------- end of: MarshalRouteDTO

@JsonObject('MessageDTO')
export class MessageDTO {
	static DEFAULT_PREVIEW_MESSAGE_LENGTH = 0;
	@JsonProperty('mID', String)
	mID: string;
	@JsonProperty('recepientUserID', String)
	recepientUserID: string;
	@JsonProperty('senderUserID', String)
	senderUserID: string;
	@JsonProperty('messageBody', String)
	messageBody: string;
	@JsonProperty('mDate', String)
	mDate: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('notification', Boolean)
	notification: boolean;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: MessageDTO

@JsonObject('PanicDTO')
export class PanicDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('panicID', String)
	panicID: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('panicType', String)
	panicType: string;
}


// ------------------- end of: PanicDTO

@JsonObject('PanicOverDTO')
export class PanicOverDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('panicID', String)
	panicID: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('panicType', String)
	panicType: string;
}


// ------------------- end of: PanicOverDTO

@JsonObject('PatrollerDTO')
export class PatrollerDTO {
	@JsonProperty('patrollerID', Number)
	patrollerID: number;
	@JsonProperty('gcmID', String)
	gcmID: string;
	@JsonProperty('address', String)
	address: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('phone', String)
	phone: string;
	@JsonProperty('password', String)
	password: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('idNo', String)
	idNo: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: PatrollerDTO

@JsonObject('PhotoDTO')
export class PhotoDTO {
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('photoID', String)
	photoID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('incidentID', String)
	incidentID: string;
	@JsonProperty('announcementID', String)
	announcementID: string;
	@JsonProperty('stringDateTaken', String)
	stringDateTaken: string;
	@JsonProperty('stringDateUploaded', String)
	stringDateUploaded: string;
	@JsonProperty('dateTaken', Number)
	dateTaken: number;
	@JsonProperty('dateUploaded', Number)
	dateUploaded: number;
	@JsonProperty('width', Number)
	width: number;
	@JsonProperty('height', Number)
	height: number;
	@JsonProperty('bytes', Number)
	bytes: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('defaultPhoto', Boolean)
	defaultPhoto: boolean;
	@JsonProperty('url', String)
	url: string;
	@JsonProperty('filePath', String)
	filePath: string;
	@JsonProperty('caption', String)
	caption: string;
	@JsonProperty('photoType', Number)
	photoType: number;
	static ASSOCIATION = 0;
	static ROUTE = 0;
	static LANDMARK = 0;
	static USER = 0;
	static CITY = 0;
	static COUNTRY = 0;
	static VEHICLE = 0;
	static INCIDENT = 0;
	static ANNOUNCEMENT = 0;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: PhotoDTO

@JsonObject('PickUpDTO')
export class PickUpDTO {
	@JsonProperty('pickupDate', Number)
	pickupDate: number;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('ownerName', String)
	ownerName: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('stringPickUpDate', String)
	stringPickUpDate: string;
	@JsonProperty('pickUpID', String)
	pickUpID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('marshalName', String)
	marshalName: string;
	@JsonProperty('commuterRequestID', String)
	commuterRequestID: string;
	@JsonProperty('userFCMtoken', String)
	userFCMtoken: string;
	@JsonProperty()
	vehicle: VehicleDTO;
}


// ------------------- end of: PickUpDTO

@JsonObject('PlaceDTO')
export class PlaceDTO {
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('googlePlaceID', String)
	googlePlaceID: string;
	@JsonProperty('placeID', String)
	placeID: string;
	@JsonProperty('address', String)
	address: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: PlaceDTO

@JsonObject('ProblemResolvedDTO')
export class ProblemResolvedDTO {
	@JsonProperty('problemResolvedID', String)
	problemResolvedID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('message', String)
	message: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('stringProblemDate', String)
	stringProblemDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('problemDate', Number)
	problemDate: number;
	@JsonProperty('apologyID', String)
	apologyID: string;
}


// ------------------- end of: ProblemResolvedDTO

@JsonObject('ProvinceDTO')
export class ProvinceDTO {
	@JsonProperty('provinceID', String)
	provinceID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: ProvinceDTO

@JsonObject('RankAggregateRatingDTO')
export class RankAggregateRatingDTO {
}


// ------------------- end of: RankAggregateRatingDTO

@JsonObject('RatingDTO')
export class RatingDTO {
	static DRIVER = 0;
	static TRIP = 0;
	static LANDMARK = 0;
	static VEHICLE = 0;
	static OVERALL_EXPERIENCE = 0;
	static SAFETY_RATING = 0;
	static QUESTION_RATING = 0;
	static TERRIBLE = 0;
	static POOR = 0;
	static AVERAGE = 0;
	static GOOD = 0;
	static EXCELLENT = 0;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('tripID', String)
	tripID: string;
	@JsonProperty('ratingID', String)
	ratingID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('remarks', String)
	remarks: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('ratingTypeName', String)
	ratingTypeName: string;
	@JsonProperty('answer', String)
	answer: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('ratingDate', String)
	ratingDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('day', Number)
	day: number;
	@JsonProperty('month', Number)
	month: number;
	@JsonProperty('year', Number)
	year: number;
}


// ------------------- end of: RatingDTO

@JsonObject('RatingLevelDTO')
export class RatingLevelDTO {
	@JsonProperty('number', Number)
	number: number;
	@JsonProperty('description', String)
	description: string;
}


// ------------------- end of: RatingLevelDTO

@JsonObject('RatingTypeAggregateDTO')
export class RatingTypeAggregateDTO {
}


// ------------------- end of: RatingTypeAggregateDTO

@JsonObject('RatingTypeDTO')
export class RatingTypeDTO {
	@JsonProperty('key', Number)
	key: number;
	@JsonProperty('name', String)
	name: string;
}


// ------------------- end of: RatingTypeDTO

@JsonObject('RemoteConfigDTO')
export class RemoteConfigDTO {
	@JsonProperty('driversUUID', String)
	driversUUID: string;
	@JsonProperty('marshalsUUID', String)
	marshalsUUID: string;
	@JsonProperty('patrollersUUID', String)
	patrollersUUID: string;
	@JsonProperty('commutersUUID', String)
	commutersUUID: string;
	@JsonProperty('routeBuildersUUID', String)
	routeBuildersUUID: string;
}


// ------------------- end of: RemoteConfigDTO

@JsonObject('RouteBuilderLocationRequestDTO')
export class RouteBuilderLocationRequestDTO {
	@JsonProperty('routeBuilderLocationRequestID', String)
	routeBuilderLocationRequestID: string;
	@JsonProperty('from', String)
	from: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: RouteBuilderLocationRequestDTO

@JsonObject('RouteBuilderLocationResponseDTO')
export class RouteBuilderLocationResponseDTO {
	@JsonProperty('routeBuilderLocationResponseID', String)
	routeBuilderLocationResponseID: string;
	@JsonProperty('message', String)
	message: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('from', String)
	from: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('builderName', String)
	builderName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: RouteBuilderLocationResponseDTO

@JsonObject('RouteBuilderMessageDTO')
export class RouteBuilderMessageDTO {
	@JsonProperty('routeBuilderMessageID', String)
	routeBuilderMessageID: string;
	@JsonProperty('title', String)
	title: string;
	@JsonProperty('message', String)
	message: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('from', String)
	from: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: RouteBuilderMessageDTO

@JsonObject('RouteDTO')
export class RouteDTO {
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('provinceID', String)
	provinceID: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('countryName', String)
	countryName: string;
	@JsonProperty('routeNumber', String)
	routeNumber: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('color', String)
	color: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('cacheDate', Number)
	cacheDate: number;
	@JsonProperty()
	routeBuilder: UserDTO;


//**** Handle this list: landmarkList

	@JsonProperty()
	builder: UserDTO;
}


// ------------------- end of: RouteDTO

@JsonObject('RoutePointDTO')
export class RoutePointDTO {
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
}


// ------------------- end of: RoutePointDTO

@JsonObject('RouteSnippetDTO')
export class RouteSnippetDTO {
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('nickName', String)
	nickName: string;
}


// ------------------- end of: RouteSnippetDTO

@JsonObject('RouteUpdateTriggerDTO')
export class RouteUpdateTriggerDTO {
	@JsonProperty('routeUpdateTriggerID', String)
	routeUpdateTriggerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: RouteUpdateTriggerDTO

@JsonObject('SafetyAggregateRatingDTO')
export class SafetyAggregateRatingDTO {
}


// ------------------- end of: SafetyAggregateRatingDTO

@JsonObject('SearchVehicleDTO')
export class SearchVehicleDTO {
	@JsonProperty('vehicleID', Number)
	vehicleID: number;
	@JsonProperty('reg', String)
	reg: string;
}


// ------------------- end of: SearchVehicleDTO

@JsonObject('SpatialInfoDTO')
export class SpatialInfoDTO {
	@JsonProperty('estimatedTime', Number)
	estimatedTime: number;
	@JsonProperty('distance', Number)
	distance: number;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('distanceID', String)
	distanceID: string;
	@JsonProperty('codedPath', String)
	codedPath: string;
	@JsonProperty('stringEstimatedTime', String)
	stringEstimatedTime: string;
	@JsonProperty('stringDistance', String)
	stringDistance: string;
	@JsonProperty()
	fromLandmark: LandmarkDTO;
	@JsonProperty()
	toLandmark: LandmarkDTO;
}


// ------------------- end of: SpatialInfoDTO

@JsonObject('StoppingVehicleDTO')
export class StoppingVehicleDTO {
	@JsonProperty('stoppingVehicleID', String)
	stoppingVehicleID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	user: UserDTO;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: StoppingVehicleDTO

@JsonObject('TaxiFeesDTO')
export class TaxiFeesDTO {
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('patrollerID', String)
	patrollerID: string;
	@JsonProperty('taxiFeesID', String)
	taxiFeesID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('adminID', String)
	adminID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('amount', Number)
	amount: number;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	driver: UserDTO;
	@JsonProperty()
	marshal: UserDTO;
	@JsonProperty()
	patroller: UserDTO;
	@JsonProperty()
	administrator: UserDTO;
	@JsonProperty()
	owner: UserDTO;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: TaxiFeesDTO

@JsonObject('TravelBuddyDTO')
export class TravelBuddyDTO {
	@JsonProperty('travelBuddyID', String)
	travelBuddyID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('buddyID', String)
	buddyID: string;
	@JsonProperty('buddyName', String)
	buddyName: string;
	@JsonProperty('buddyEmail', String)
	buddyEmail: string;
	@JsonProperty('buddyPhone', String)
	buddyPhone: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('buddyFCMtoken', String)
	buddyFCMtoken: string;
	@JsonProperty('active', Boolean)
	active: boolean;
}


// ------------------- end of: TravelBuddyDTO

@JsonObject('TripDTO')
export class TripDTO {
	@JsonProperty('tripID', String)
	tripID: string;
	@JsonProperty('marshalID', String)
	marshalID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('numberOfPassengers', Number)
	numberOfPassengers: number;
	@JsonProperty('dateDispatched', Number)
	dateDispatched: number;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty()
	marshall: UserDTO;
	@JsonProperty()
	driver: UserDTO;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('stringDateDispatched', String)
	stringDateDispatched: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('associatioName', String)
	associatioName: string;
	@JsonProperty('scanned', Boolean)
	scanned: boolean;
}


// ------------------- end of: TripDTO

@JsonObject('TripLogDTO')
export class TripLogDTO {
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('tripStartDate', Number)
	tripStartDate: number;
	@JsonProperty('tripLogID', String)
	tripLogID: string;
	@JsonProperty('tripID', String)
	tripID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('dispatchVehicleID', String)
	dispatchVehicleID: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('dispatchLandmarkID', String)
	dispatchLandmarkID: string;
	@JsonProperty('dispatchLandmarkName', String)
	dispatchLandmarkName: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	driver: UserDTO;
}


// ------------------- end of: TripLogDTO

@JsonObject('UserArrivedAtWorkDTO')
export class UserArrivedAtWorkDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userDescription', String)
	userDescription: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('userType', Number)
	userType: number;
}


// ------------------- end of: UserArrivedAtWorkDTO

@JsonObject('UserDTO')
export class UserDTO {
	@JsonProperty('userType', Number)
	userType: number;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('uid', String)
	uid: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('email', String)
	email: string;
	@JsonProperty('cellphone', String)
	cellphone: string;
	@JsonProperty('password', String)
	password: string;
	@JsonProperty('userDescription', String)
	userDescription: string;
	@JsonProperty('stringDateRegistered', String)
	stringDateRegistered: string;
	@JsonProperty('hyperTrackUserID', String)
	hyperTrackUserID: string;
	@JsonProperty()
	morningLandmark: LandmarkDTO;
	@JsonProperty()
	afternoonLandmark: LandmarkDTO;
	@JsonProperty('dateRegistered', Number)
	dateRegistered: number;
	@JsonProperty('activeFlag', Boolean)
	activeFlag: boolean;
	@JsonProperty('researchConsent', Boolean)
	researchConsent: boolean;
	@JsonProperty('gender', String)
	gender: string;
	@JsonProperty('address', String)
	address: string;
	@JsonProperty('idNumber', String)
	idNumber: string;
	@JsonProperty()
	device: DeviceDTO;
	@JsonProperty()
	vehicle: VehicleDTO;
}


// ------------------- end of: UserDTO

@JsonObject('UserFinishedWalkingDTO')
export class UserFinishedWalkingDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userDescription', String)
	userDescription: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('userType', Number)
	userType: number;
}


// ------------------- end of: UserFinishedWalkingDTO

@JsonObject('UserLeftWorkDTO')
export class UserLeftWorkDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userDescription', String)
	userDescription: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('userType', Number)
	userType: number;
}


// ------------------- end of: UserLeftWorkDTO

@JsonObject('UserWalkingDTO')
export class UserWalkingDTO {
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('name', String)
	name: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('userDescription', String)
	userDescription: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('userType', Number)
	userType: number;
}


// ------------------- end of: UserWalkingDTO

@JsonObject('VehicleAggregateRatingDTO')
export class VehicleAggregateRatingDTO {
}


// ------------------- end of: VehicleAggregateRatingDTO

@JsonObject('VehicleArrivalDTO')
export class VehicleArrivalDTO {
	@JsonProperty('arrivalID', String)
	arrivalID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('routeName', String)
	routeName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateArrived', Number)
	dateArrived: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty('dispatched', Boolean)
	dispatched: boolean;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: VehicleArrivalDTO

@JsonObject('VehicleDTO')
export class VehicleDTO {
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('ownerName', String)
	ownerName: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('licenceExpiryDate', Number)
	licenceExpiryDate: number;
	@JsonProperty('policyIssueDate', Number)
	policyIssueDate: number;
	@JsonProperty('policyExpiryDate', Number)
	policyExpiryDate: number;
	@JsonProperty('cacheDate', Number)
	cacheDate: number;
	@JsonProperty()
	vehicleType: VehicleTypeDTO;


//**** Handle this list: photoList

	@JsonProperty('year', String)
	year: string;
	@JsonProperty('operatingLicence', String)
	operatingLicence: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('policyNumber', String)
	policyNumber: string;
	@JsonProperty('selected', Boolean)
	selected: boolean;
	@JsonProperty()
	builder: UserDTO;
	@JsonProperty('ACTIVE', String)
	ACTIVE: string;
	@JsonProperty('IN_ACTIVE', String)
	IN_ACTIVE: string;
	@JsonProperty('SUSPENDED', String)
	SUSPENDED: string;
}


// ------------------- end of: VehicleDTO

@JsonObject('VehicleDepartureDTO')
export class VehicleDepartureDTO {
	@JsonProperty('departureID', String)
	departureID: string;
	@JsonProperty('landmarkID', String)
	landmarkID: string;
	@JsonProperty('landmarkName', String)
	landmarkName: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('driverName', String)
	driverName: string;
	@JsonProperty('cityID', String)
	cityID: string;
	@JsonProperty('cityName', String)
	cityName: string;
	@JsonProperty('routeID', String)
	routeID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('associationName', String)
	associationName: string;
	@JsonProperty('countryID', String)
	countryID: string;
	@JsonProperty('dateDeparted', Number)
	dateDeparted: number;
	@JsonProperty()
	vehicle: VehicleDTO;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty()
	device: DeviceDTO;
}


// ------------------- end of: VehicleDepartureDTO

@JsonObject('VehicleDrivingDTO')
export class VehicleDrivingDTO {
	@JsonProperty('vehicleDrivingID', String)
	vehicleDrivingID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('nearestAddress', String)
	nearestAddress: string;
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	vehicleType: VehicleTypeDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('viaAwarenessAPI', Boolean)
	viaAwarenessAPI: boolean;
	@JsonProperty('viaNeura', Boolean)
	viaNeura: boolean;
	@JsonProperty('viaHypertrack', Boolean)
	viaHypertrack: boolean;
	@JsonProperty('beaconFound', Boolean)
	beaconFound: boolean;
	@JsonProperty('starting', Boolean)
	starting: boolean;
	@JsonProperty('stopping', Boolean)
	stopping: boolean;
	@JsonProperty('moving', Boolean)
	moving: boolean;
}


// ------------------- end of: VehicleDrivingDTO

@JsonObject('VehicleFinishedDrivingDTO')
export class VehicleFinishedDrivingDTO {
	@JsonProperty('vehicleFinishedDrivingID', String)
	vehicleFinishedDrivingID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('ownerID', String)
	ownerID: string;
	@JsonProperty('associationID', String)
	associationID: string;
	@JsonProperty('nearestAddress', String)
	nearestAddress: string;
	@JsonProperty('beaconName', String)
	beaconName: string;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	vehicleType: VehicleTypeDTO;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('viaAwarenessAPI', Boolean)
	viaAwarenessAPI: boolean;
	@JsonProperty('viaNeura', Boolean)
	viaNeura: boolean;
	@JsonProperty('viaHypertrack', Boolean)
	viaHypertrack: boolean;
	@JsonProperty('beaconFound', Boolean)
	beaconFound: boolean;
}


// ------------------- end of: VehicleFinishedDrivingDTO

@JsonObject('VehicleInfoDTO')
export class VehicleInfoDTO {
	@JsonProperty('vehicleProfileID', Number)
	vehicleProfileID: number;
	@JsonProperty('type', String)
	type: string;
	@JsonProperty('year', String)
	year: string;
	@JsonProperty('make', String)
	make: string;
	@JsonProperty('capacity', Number)
	capacity: number;
	@JsonProperty('operatingLicence', String)
	operatingLicence: string;
	@JsonProperty('operatingLicenceExpDate', Number)
	operatingLicenceExpDate: number;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('status', String)
	status: string;
	@JsonProperty('vehicleID', Number)
	vehicleID: number;
}


// ------------------- end of: VehicleInfoDTO

@JsonObject('VehicleLocationRequestDTO')
export class VehicleLocationRequestDTO {
	@JsonProperty('vehicleLocationRequestID', String)
	vehicleLocationRequestID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
}


// ------------------- end of: VehicleLocationRequestDTO

@JsonObject('VehicleLocationResponseDTO')
export class VehicleLocationResponseDTO {
	@JsonProperty('vehicleLocationResponseID', String)
	vehicleLocationResponseID: string;
	@JsonProperty('vehicleID', String)
	vehicleID: string;
	@JsonProperty('vehicleReg', String)
	vehicleReg: string;
	@JsonProperty('userID', String)
	userID: string;
	@JsonProperty('driverID', String)
	driverID: string;
	@JsonProperty('stringDate', String)
	stringDate: string;
	@JsonProperty('userName', String)
	userName: string;
	@JsonProperty('fcmToken', String)
	fcmToken: string;
	@JsonProperty('date', Number)
	date: number;
	@JsonProperty('latitude', Number)
	latitude: number;
	@JsonProperty('longitude', Number)
	longitude: number;
	@JsonProperty()
	vehicle: VehicleDTO;
}


// ------------------- end of: VehicleLocationResponseDTO

@JsonObject('VehicleTypeDTO')
export class VehicleTypeDTO {
	@JsonProperty('capacity', Number)
	capacity: number;
	@JsonProperty('vehicleTypeID', String)
	vehicleTypeID: string;
	@JsonProperty('make', String)
	make: string;
	@JsonProperty('model', String)
	model: string;
	@JsonProperty('countryID', String)
	countryID: string;
}


// ------------------- end of: VehicleTypeDTO

